/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication31;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.awt.Font;
import static java.awt.Font.BOLD;
import static java.awt.Font.PLAIN;
import java.awt.FontMetrics;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.print.PageFormat;
import java.awt.print.Paper;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import javax.swing.ImageIcon;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Thilinika
 */
public class Pay extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    Connection con =null;
    PreparedStatement pst=null;
    ResultSet rs=null;
    
    
   // String billNo="";
  /*  Double NetTotal=0.0;
    Double Discount=0.0;
    Double TotalPayment=0.0;
    Double bHeight=0.0;
    
    ArrayList<String> Hall=new ArrayList<>();
    ArrayList<String> Room=new ArrayList<>();
    ArrayList<String> Order=new ArrayList<>();
    ArrayList<String> AdditionalService=new ArrayList<>();
    ArrayList<String> subtotal=new ArrayList<>();
    
    */
    
    public Pay() {
        initComponents();
        this.setLocationRelativeTo(this);//center form
        table_update();
        
        con =DBconnect.connect();
        
    //    tableload();
        
    }
   /* public ArrayList<User> UserList(){
    
        ArrayList<User> userList = new ArrayList<>();
        try{
        
            Class.forName("com.mysql.jdbc.Driver");
            con =DriverManager.getConnection("jdbc:mysql://localhost:3307/example?","root","");
            String query1="SELECT * FROM table2";
            Statement st=con.createStatement();
            ResultSet rs=st.executeQuery(query1);
            
            User user;
            while(rs.next()){
                
               // user =new User(rs.getInt("pid"),rs.getString("pname"),rs.getInt("phall"),rs.getInt("proom"),rs.getInt("porder"),rs.getInt("padservice"),rs.getString("pmeth"),rs.getInt("total"));
            }
            
            
        }
        catch(Exception e){
            
            System.out.println(e);
        }
        
        return null;
    }
    */
  /*  public void tableload()
    {
       
        try {
            String sql=" SELECT pid,pname,phall,proom,porder,padservice,pmeth,total FROM table2";
            pst=con.prepareStatement(sql);
            rs=pst.executeQuery();
            
            jTable1.setModel(Dbutils.resultSetTotableModel(rs));
            
            
        } catch (SQLException ex) {
            Logger.getLogger(Pay.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }*/

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
       
        
        
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        searchBOX = new javax.swing.JTextField();
        pn1 = new javax.swing.JLabel();
        nameBOX = new javax.swing.JTextField();
        pn2 = new javax.swing.JLabel();
        pn3 = new javax.swing.JLabel();
        pn4 = new javax.swing.JLabel();
        pn5 = new javax.swing.JLabel();
        pn6 = new javax.swing.JLabel();
        NetTotalBox = new javax.swing.JTextField();
        AdBox = new javax.swing.JTextField();
        orderBox = new javax.swing.JTextField();
        roomBOX = new javax.swing.JTextField();
        hallBOX = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        pn7 = new javax.swing.JLabel();
        pn8 = new javax.swing.JLabel();
        DiscountBox = new javax.swing.JTextField();
        TotalPaymentBox = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 143, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 102, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(java.awt.SystemColor.desktop);
        setForeground(new java.awt.Color(0, 102, 102));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(153, 255, 153));

        jTable1.setBackground(new java.awt.Color(204, 255, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Hall", "Room", "Order", "Additional Service", "Net Total", "Discount", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        searchBOX.setBackground(new java.awt.Color(153, 153, 153));
        searchBOX.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchBOXKeyReleased(evt);
            }
        });

        pn1.setBackground(new java.awt.Color(0, 0, 0));
        pn1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        pn1.setText("Name");

        nameBOX.setBackground(new java.awt.Color(153, 153, 153));
        nameBOX.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N

        pn2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        pn2.setText("Hall payment");

        pn3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        pn3.setText("Room payment");

        pn4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        pn4.setText("Order payment");

        pn5.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        pn5.setText("Additional service payment");

        pn6.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        pn6.setText("Net Total ");

        NetTotalBox.setBackground(new java.awt.Color(153, 153, 153));
        NetTotalBox.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        NetTotalBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NetTotalBoxActionPerformed(evt);
            }
        });

        AdBox.setBackground(new java.awt.Color(153, 153, 153));
        AdBox.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N

        orderBox.setBackground(new java.awt.Color(153, 153, 153));
        orderBox.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N

        roomBOX.setBackground(new java.awt.Color(153, 153, 153));
        roomBOX.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N

        hallBOX.setBackground(new java.awt.Color(153, 153, 153));
        hallBOX.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N

        jButton2.setBackground(new java.awt.Color(153, 204, 0));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("+");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(153, 204, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton1.setText("ADD");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(153, 204, 0));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton4.setText("UPDATE");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(153, 204, 0));
        jButton5.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton5.setText("DELETE");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton9.setBackground(new java.awt.Color(153, 204, 0));
        jButton9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton9.setText("PAY");
        jButton9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton9MouseClicked(evt);
            }
        });
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        pn7.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        pn7.setText("Discount");

        pn8.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        pn8.setText("Total Payment");

        DiscountBox.setBackground(new java.awt.Color(153, 153, 153));
        DiscountBox.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        DiscountBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DiscountBoxActionPerformed(evt);
            }
        });

        TotalPaymentBox.setBackground(new java.awt.Color(153, 153, 153));
        TotalPaymentBox.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        TotalPaymentBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TotalPaymentBoxActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(153, 204, 0));
        jButton6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton6.setText("PRINT");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton10.setBackground(new java.awt.Color(153, 204, 0));
        jButton10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton10.setText("DEMO");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Thilinika\\Pictures\\Screenshots\\Screenshot (594).png")); // NOI18N
        jLabel2.setText("jLabel2");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pn3)
                            .addComponent(pn2)
                            .addComponent(pn1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 322, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 678, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(jButton5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton6)
                        .addGap(77, 77, 77))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(searchBOX, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pn5)
                                    .addComponent(pn6)
                                    .addComponent(pn7)
                                    .addComponent(pn8)
                                    .addComponent(pn4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(DiscountBox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                                    .addComponent(NetTotalBox)
                                    .addComponent(AdBox)
                                    .addComponent(orderBox)
                                    .addComponent(roomBOX)
                                    .addComponent(hallBOX)
                                    .addComponent(nameBOX)
                                    .addComponent(TotalPaymentBox))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton2)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jButton9)
                                        .addGap(32, 32, 32)
                                        .addComponent(jButton10)))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(searchBOX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pn1)
                            .addComponent(nameBOX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pn2)
                            .addComponent(hallBOX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pn3)
                            .addComponent(roomBOX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pn4)
                            .addComponent(orderBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pn5)
                            .addComponent(AdBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pn6)
                            .addComponent(NetTotalBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(pn7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(DiscountBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addGap(79, 79, 79)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TotalPaymentBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(pn8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(80, 80, 80))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(54, 54, 54))))))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 136, 1230, 630));

        jPanel3.setBackground(new java.awt.Color(153, 255, 153));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication31/images (2).jpg"))); // NOI18N
        jLabel9.setText("jLabel9");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 102));
        jLabel4.setText("Payment");

        jButton8.setBackground(new java.awt.Color(153, 204, 0));
        jButton8.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton8.setText("Logout");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 403, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(463, 463, 463)
                .addComponent(jButton8)
                .addGap(63, 63, 63))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9)))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 1230, 90));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication31/000.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, -4, 1350, 830));

        pack();
    }// </editor-fold>//GEN-END:initComponents
        
    
        Connection con1;
        PreparedStatement insert;
        
        private void table_update()
        {
            int c;
            
             try {
            Class.forName("com.mysql.jdbc.Driver");
            con1=DriverManager.getConnection("jdbc:mysql://localhost:3307/database", "root", "");
            insert=con1.prepareStatement("select * from table1");
            ResultSet rs=insert.executeQuery();
            
                ResultSetMetaData Rss =rs.getMetaData();
                c=Rss.getColumnCount();
                
                DefaultTableModel Dt=(DefaultTableModel)jTable1.getModel();
                
                    Dt.setRowCount(0);
            
                    while(rs.next())
                    {
                        Vector v2=new Vector();
                        
                        for(int a=1; a<=c ;a++)
                        {
                            v2.add(rs.getString("PID"));
                            v2.add(rs.getString("Name"));
                            v2.add(rs.getString("HallPayment"));
                            v2.add(rs.getString("RoomPayment"));
                            v2.add(rs.getString("OrderPayment"));
                            v2.add(rs.getString("AdPayment"));
                            v2.add(rs.getString("NetTotal"));
                            v2.add(rs.getString("Discount"));
                            v2.add(rs.getString("TotalPayment"));
                            
                        }
                        
                        Dt.addRow(v2);
                    }
            
            /*  try {
            String sql="INSERT INTO table1"+
            "(Name,HallPayment,RoomPayment,OrderPayment,AdPayment,NetTotal,Discount,TotalPayment) "
            + " VALUES (?,?,?,?,?,?,?,?)";
            
            con = DriverManager.getConnection("jdbc:mysql://localhost:3307/database","root"," ");
            pst=con.prepareStatement(sql);
            pst.setString(1,nameBOX.getText());
            pst.setString(2,hallBOX.getText());
            pst.setString(3,roomBOX.getText());
            pst.setString(4,orderBox.getText());
            pst.setString(5,AdBox.getText());
            pst.setString(6,NetTotalBox.getText());
            pst.setString(7,DiscountBox.getText());
            pst.setString(8,TotalPaymentBox.getText());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null,"inserted successfully");
            } catch (SQLException |HeadlessException ex ) {
            JOptionPane.showMessageDialog(null,ex);
            }
            
            }
        */
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Pay.class.getName()).log(Level.SEVERE, null, ex);
        }
        catch (SQLException ex) {
            Logger.getLogger(Pay.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        }


    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      
        String name=nameBOX.getText();
        String hall=hallBOX.getText();
        String room=roomBOX.getText();
        String order=orderBox.getText();
        String ad=AdBox.getText();
        String NetTotal=NetTotalBox.getText();
        String Discount=DiscountBox.getText();
        String TotalPayment=TotalPaymentBox.getText();
       
        

        try {
            Class.forName("com.mysql.jdbc.Driver");
            con1=DriverManager.getConnection("jdbc:mysql://localhost:3307/database", "root", "");
            insert=con1.prepareStatement("insert into table1(Name,HallPayment,RoomPayment,OrderPayment,AdPayment,NetTotal,Discount,TotalPayment)values(?,?,?,?,?,?,?,?)");
            
            insert.setString(1, name);
            insert.setString(2, hall);
            insert.setString(3, room);
            insert.setString(4, order);
            insert.setString(5, ad);
            insert.setString(6, NetTotal);
            insert.setString(7, Discount);
            insert.setString(8, TotalPayment);
            
            insert.executeUpdate();
            
            JOptionPane.showMessageDialog(this, "Record Addedd");
            table_update();
            
            nameBOX.setText("");
            hallBOX.setText("");
            roomBOX.setText("");
            orderBox.setText("");
            AdBox.setText("");
            NetTotalBox.setText("");
            DiscountBox.setText("");
            TotalPaymentBox.setText("");
            nameBOX.requestFocus();

            
            
            /*  try {
            String sql="INSERT INTO table1"+
            "(Name,HallPayment,RoomPayment,OrderPayment,AdPayment,NetTotal,Discount,TotalPayment) "
            + " VALUES (?,?,?,?,?,?,?,?)";
            
            con = DriverManager.getConnection("jdbc:mysql://localhost:3307/database","root"," ");
            pst=con.prepareStatement(sql);
            pst.setString(1,nameBOX.getText());
            pst.setString(2,hallBOX.getText());
            pst.setString(3,roomBOX.getText());
            pst.setString(4,orderBox.getText());
            pst.setString(5,AdBox.getText());
            pst.setString(6,NetTotalBox.getText());
            pst.setString(7,DiscountBox.getText());
            pst.setString(8,TotalPaymentBox.getText());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null,"inserted successfully");
            } catch (SQLException |HeadlessException ex ) {
            JOptionPane.showMessageDialog(null,ex);
            }
            
            }
        */
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Pay.class.getName()).log(Level.SEVERE, null, ex);
        }
        catch (SQLException ex) {
            Logger.getLogger(Pay.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

      
      
        
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       float a,b,c,d,e,f,g;
        
       
        a=Float.parseFloat(hallBOX.getText());
        b=Float.parseFloat(roomBOX.getText());
        c=Float.parseFloat(orderBox.getText());
        d=Float.parseFloat(AdBox.getText());
        
        e=a+b+c+d;
        
        NetTotalBox.setText(""+e);
        
        /*
        if(promotion == silver)
        {
            f=(float)(e*0.5);
        }
        else if(promotion == gold)
        {
            f=(float)(e*0.8);
        }
        else(promotion == platinum)
        {
            f=float(e*0.10);
        }
        
        */
        
        f=(float) (e*0.02);
        
        DiscountBox.setText(""+f);
        
        g=e-f;
        TotalPaymentBox.setText(""+g);
       
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void NetTotalBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NetTotalBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NetTotalBoxActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel Dt=(DefaultTableModel)jTable1.getModel();
        int selectedIndex =jTable1.getSelectedRow();
        
         try {
             
                int id=Integer.parseInt(Dt.getValueAt(selectedIndex,0).toString());
                String name=nameBOX.getText();
                String hall=hallBOX.getText();
                String room=roomBOX.getText();
                String order=orderBox.getText();
                String ad=AdBox.getText();
                String NetTotal=NetTotalBox.getText();
                String Discount=DiscountBox.getText();
                String TotalPayment=TotalPaymentBox.getText();

             
            Class.forName("com.mysql.jdbc.Driver");
            con1=DriverManager.getConnection("jdbc:mysql://localhost:3307/database", "root", "");
            insert=con1.prepareStatement("update table1 set Name=?,HallPayment=?,RoomPayment=?,OrderPayment=?,AdPayment=?,NetTotal=?,Discount=?,TotalPayment=? where PID=?");
            
            insert.setString(1, name);
            insert.setString(2, hall);
            insert.setString(3, room);
            insert.setString(4, order);
            insert.setString(5, ad);
            insert.setString(6, NetTotal);
            insert.setString(7, Discount);
            insert.setString(8, TotalPayment);
            insert.setInt(9, id);
            
            insert.executeUpdate();
            
            
            
            JOptionPane.showMessageDialog(this, "Record update");
            table_update();
            
            nameBOX.setText("");
            hallBOX.setText("");
            roomBOX.setText("");
            orderBox.setText("");
            AdBox.setText("");
            NetTotalBox.setText("");
            DiscountBox.setText("");
            TotalPaymentBox.setText("");
            nameBOX.requestFocus();

            
            
            /*  try {
            String sql="INSERT INTO table1"+
            "(Name,HallPayment,RoomPayment,OrderPayment,AdPayment,NetTotal,Discount,TotalPayment) "
            + " VALUES (?,?,?,?,?,?,?,?)";
            
            con = DriverManager.getConnection("jdbc:mysql://localhost:3307/database","root"," ");
            pst=con.prepareStatement(sql);
            pst.setString(1,nameBOX.getText());
            pst.setString(2,hallBOX.getText());
            pst.setString(3,roomBOX.getText());
            pst.setString(4,orderBox.getText());
            pst.setString(5,AdBox.getText());
            pst.setString(6,NetTotalBox.getText());
            pst.setString(7,DiscountBox.getText());
            pst.setString(8,TotalPaymentBox.getText());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null,"inserted successfully");
            } catch (SQLException |HeadlessException ex ) {
            JOptionPane.showMessageDialog(null,ex);
            }
            
            }
        */
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Pay.class.getName()).log(Level.SEVERE, null, ex);
        }
        catch (SQLException ex) {
            Logger.getLogger(Pay.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        
        DefaultTableModel Dt=(DefaultTableModel)jTable1.getModel();
        int selectedIndex =jTable1.getSelectedRow();
        
         nameBOX.setText(Dt.getValueAt(selectedIndex, 1).toString());
         hallBOX.setText(Dt.getValueAt(selectedIndex, 2).toString());
         roomBOX.setText(Dt.getValueAt(selectedIndex, 3).toString());
         orderBox.setText(Dt.getValueAt(selectedIndex, 4).toString());
         AdBox.setText(Dt.getValueAt(selectedIndex, 5).toString());
         NetTotalBox.setText(Dt.getValueAt(selectedIndex, 6).toString());
         DiscountBox.setText(Dt.getValueAt(selectedIndex, 7).toString());
         TotalPaymentBox.setText(Dt.getValueAt(selectedIndex, 8).toString());
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton9MouseClicked
        Card cs = new Card();
        //cs.setVisible(true);
        cs.pack();
        cs.setLocationRelativeTo(null);
        cs.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
        
        String msg=TotalPaymentBox.getText();
       new Card(msg).setVisible(true);
    }//GEN-LAST:event_jButton9MouseClicked

    private void DiscountBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DiscountBoxActionPerformed
     
        
        
    }//GEN-LAST:event_DiscountBoxActionPerformed

    private void TotalPaymentBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TotalPaymentBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TotalPaymentBoxActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel Dt=(DefaultTableModel)jTable1.getModel();
        int selectedIndex =jTable1.getSelectedRow();
        
        try {
             
                int id=Integer.parseInt(Dt.getValueAt(selectedIndex,0).toString());
                
                int dialogResult=JOptionPane.showConfirmDialog(null,"Do you want to delete the Record?","Warning",JOptionPane.YES_NO_OPTION);
                
                if(dialogResult ==JOptionPane.YES_OPTION)
                {
                Class.forName("com.mysql.jdbc.Driver");
                con1=DriverManager.getConnection("jdbc:mysql://localhost:3307/database", "root", "");
                insert=con1.prepareStatement("delete from table1 where PID=?");

              
                insert.setInt(1, id);
                
                insert.executeUpdate();
            
            
            
                JOptionPane.showMessageDialog(this, "Record Deleted");
                table_update();

                nameBOX.setText("");
                hallBOX.setText("");
                roomBOX.setText("");
                orderBox.setText("");
                AdBox.setText("");
                NetTotalBox.setText("");
                DiscountBox.setText("");
                TotalPaymentBox.setText("");
                nameBOX.requestFocus();
                
                }
                
                

           
            
           
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Pay.class.getName()).log(Level.SEVERE, null, ex);
        }
        catch (SQLException ex) {
            Logger.getLogger(Pay.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void searchBOXKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchBOXKeyReleased
       try{
       
           String sql="select * from table1 where PID=?";
           
           pst=con1.prepareStatement(sql);
           pst.setString(1,searchBOX.getText());
           
           rs=pst.executeQuery();
           
           if(rs.next()){
           
               String add1=rs.getString("Name");
               nameBOX.setText(add1);
               String add2=rs.getString("HallPayment");
               hallBOX.setText(add2);
               String add3=rs.getString("RoomPayment");
               roomBOX.setText(add3);
               String add4=rs.getString("OrderPayment");
               orderBox.setText(add4);
               String add5=rs.getString("AdPayment");
               AdBox.setText(add5);
               String add6=rs.getString("NetTotal");
               NetTotalBox.setText(add6);
               String add7=rs.getString("Discount");
               DiscountBox.setText(add7);
               String add8=rs.getString("TotalPayment");
               TotalPaymentBox.setText(add8);
             
           }
           
       
       }catch(Exception e){
       
           JOptionPane.showMessageDialog(this, "Incorrect ID!!");
       
       }
    }//GEN-LAST:event_searchBOXKeyReleased

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        
       
      // String msg=TotalPaymentBox.getText();
       //new Card(msg).setVisible(true);
        
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        try {
            /* PrinterJob pj=PrinterJob.getPrinterJob();
            pj.setPrintable(new BillPrintable(), getPageFormat(pj));
            
            try{
            pj.print();
            }
            catch(PrinterException ex)
            {
            ex.printStackTrace();
            }*/
            
            Class.forName("com.mysql.jdbc.Driver");
            con=DriverManager.getConnection("jdbc:mysql://localhost:3307/database","root","");
            JasperDesign jdesign=JRXmlLoader.load("C:\\Users\\Thilinika\\Documents\\NetBeansProjects\\JavaApplication31\\src\\javaapplication31\\report.jrxml");
            String query="select * from table1";
            
            JRDesignQuery updateQuery=new  JRDesignQuery();
            updateQuery.setText(query);
            
            jdesign.setQuery(updateQuery);
            
            JasperReport jreport=JasperCompileManager.compileReport(jdesign);
            JasperPrint jprint=JasperFillManager.fillReport(jreport,null,con);
            
            JasperViewer.viewReport(jprint);
            
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Pay.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Pay.class.getName()).log(Level.SEVERE, null, ex);
        } catch (JRException ex) {
            Logger.getLogger(Pay.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
                nameBOX.setText(("Mr.Nimal"));
                hallBOX.setText("15000");
                roomBOX.setText("12000");
                orderBox.setText("4000");
                AdBox.setText("3000");
        
    }//GEN-LAST:event_jButton10ActionPerformed
    
    public PageFormat getPageFormat(PrinterJob pj)
    {
        
        PageFormat pf=pj.defaultPage();
        Paper paper=pf.getPaper();
        
        double bodyHeight=8.0;
        double headerHeight=5.0;
        double footerHeight=5.0;
        double width=cn_to_pp(8);
        double height=cn_to_pp(headerHeight+bodyHeight+footerHeight);
        paper.setSize(width, height);
        paper.setImageableArea(0, 0, width,height =cn_to_pp(1));
        
        pf.setOrientation(PageFormat.PORTRAIT);
        pf.setPaper(paper);
        
        return pf;
        
    }
    
    protected static double cn_to_pp(double cm)
    {
        return toPPI(cm*0.393600787);
    }
    protected static double toPPI(double inch)
    {
        return inch*72;
    }
    
    public class BillPrintable implements Printable{

        @Override
        public int print(Graphics graphics, PageFormat pf, int pageIndex ) 
        throws PrinterException {
            
           
            int result=NO_SUCH_PAGE;
                if(pageIndex == 0){
                
                    Graphics2D g2d=(Graphics2D) graphics;
                    
                    double width=pf.getImageableWidth();
                    
                    g2d.translate((int) pf.getImageableX(),(int) pf.getImageableY());
                    
                //    g2d.translate;
                
                    FontMetrics metrics=g2d.getFontMetrics(new Font("Arial",BOLD,7));
                    
                    
                    int idLength=metrics.stringWidth("000");
                    int amtLength=metrics.stringWidth("000000");
                    int qtyLength=metrics.stringWidth("00000");
                    int priceLength=metrics.stringWidth("000000");
                    int prodLength=(int)width-idLength-amtLength-amtLength-priceLength-17;
                    
                    int productPosition=0;
                    int discountPosition=prodLength+5;
                    int pricePosition=discountPosition+idLength+10;
                    int qtyPosition=pricePosition+priceLength+4;
                    int amountPosition=qtyPosition+qtyLength;
                    
                    
                    try{
                   
                        //Draw Header
                        int y=20;
                        int yShift=10;
                        int headerRectHeight=15;
                        int headerRectHeighta=40;
                        
                        //product name
                        String pn1a=pn1.getText();
                        String pn2a=pn2.getText();
                        String pn3a=pn3.getText();
                        String pn4a=pn4.getText();
                        String pn5a=pn5.getText();
                        String pn6a=pn6.getText();
                        String pn7a=pn7.getText();
                        
                        
                        //product price
                        Float pp1a=Float.valueOf(hallBOX.getText());
                        Float pp2a=Float.valueOf(roomBOX.getText());
                        Float pp3a=Float.valueOf(orderBox.getText());
                        Float pp4a=Float.valueOf(AdBox.getText());
                        Float pp5a=Float.valueOf(NetTotalBox.getText());
                        Float pp6a=Float.valueOf(DiscountBox.getText());
                        Float pp7a=Float.valueOf(TotalPaymentBox.getText());
                        
                        g2d.setFont(new Font("Monospaced",PLAIN,9));
                        g2d.drawString("-------------------------------", 12, y);y+=yShift;
                        g2d.drawString("    Restaurant Bill Recipt      ", 12, y);y+=yShift;
                        g2d.drawString("-------------------------------", 12, y);y+=headerRectHeight;
                    
                        g2d.drawString("-------------------------------", 10, y);y+=yShift;
                        g2d.drawString(" ITEM                   COST   ", 10, y);y+=yShift;
                        g2d.drawString("-------------------------------", 10, y);y+=headerRectHeight;
                        g2d.drawString(" "+pn1a+"             "+pp1a+" ", 10, y);y+=yShift;
                        g2d.drawString(" "+pn2a+"             "+pp2a+" ", 10, y);y+=yShift;
                        g2d.drawString(" "+pn3a+"             "+pp3a+" ", 10, y);y+=yShift;
                        g2d.drawString(" "+pn4a+"             "+pp4a+" ", 10, y);y+=yShift;
                        g2d.drawString("-------------------------------", 10, y);y+=yShift;
                        g2d.drawString(" "+pn5a+"        "+pp5a+"      ", 10, y);y+=yShift;
                        g2d.drawString(" "+pn6a+"        "+pp6a+"      ", 10, y);y+=yShift;
                        g2d.drawString(" "+pn7a+"        "+pp7a+"      ", 10, y);y+=yShift;
                        g2d.drawString("-------------------------------", 10, y);y+=yShift;
                        g2d.drawString("-------------------------------", 10, y);y+=yShift;
                        g2d.drawString("   Thanks to visit out Hotel   ", 10, y);y+=yShift;
                        
                    }catch(Exception r)
                    {
                        r.printStackTrace();
                    }  
                    result=PAGE_EXISTS;
                    
                    return result;
                        
                }
            
            
            
            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        
        
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pay().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AdBox;
    private javax.swing.JTextField DiscountBox;
    private javax.swing.JTextField NetTotalBox;
    private javax.swing.JTextField TotalPaymentBox;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JTextField hallBOX;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField nameBOX;
    private javax.swing.JTextField orderBox;
    private javax.swing.JLabel pn1;
    private javax.swing.JLabel pn2;
    private javax.swing.JLabel pn3;
    private javax.swing.JLabel pn4;
    private javax.swing.JLabel pn5;
    private javax.swing.JLabel pn6;
    private javax.swing.JLabel pn7;
    private javax.swing.JLabel pn8;
    private javax.swing.JTextField roomBOX;
    private javax.swing.JTextField searchBOX;
    // End of variables declaration//GEN-END:variables
}
